### PR TITLE
shell: replace wordToArg with sh/v3/expand

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

### CODE REVIEW

**Comment by josharian** [comment]
> (see commit messages - please do not squash)

What kind of a monster do you think I am? 😅 

---

This looks great, unsurprisingly. Thank you!!

**Comment by mvdan** [comment]
> What kind of a monster do you think I am? 😅

It's part of my "post pull request from branch" script, it wasn't particularly aimed at you :P You'd be surprised at how many projects would squash my PRs even when I had carefully written multiple commit messages.

**Comment by josharian** [comment]
Yeah. I really miss Gerrit. But the world is on GitHub. What does one do?

https://mitchellh.com/writing/github-changesets was a nice recent read on this front.

**Comment by mvdan** [comment]
we use GerritHub for the CUE repos: https://review.gerrithub.io/q/projects:cue-+is:open

the only awkwardness then is that gerrit is the git source of truth, mirroring to github, so you shouldn't merge any github PRs traight away. we wrote an `importpr` command to automate most of the importing of a PR into a CL after the review and CI on the PR has finished; so it's similar to what Go does, but we deal with the review on the PR for the sake of the contributor.

**Comment by josharian** [comment]
Yeah. Sounds nice, but that's too many moving parts for personal repos--I'd spend more time setting it up than using it. (I haven't even set up GitHub Actions, sigh.)

**Comment by mvdan** [comment]
Agreee that the overhead is too large for personal repos :) just sharing the only decent hybrid I know of.

**Comment by josharian** [comment]
Thanks!

**Pull request merged**
